### ISSUE TITLE
Possibility to forecast severity though TAF (Terminal Area Forecast) rather than METAR?

### ISSUE THREAD

**Issue by devleaks** [rebsp/atmap#1]
As en enhancement request, would it be possible to forecast the severity of weather from TAF prediction rather than METAR?
May be with a probability like:

phenomena:
6 hours -> severity 2 with probability 30%
12 hours -> severity 3 with probability 60%
...

Thank you.

**Comment by rebsp** [comment]
Hi @devleaks and thanks for creating this issue! Sorry for the delayed reply, the weekend got in the way 😉 I will look into this and keep you posted

**Comment by rebsp** [comment]
Will need a new metar parser as https://github.com/python-metar/python-metar does not support parsing TAF's

**Comment by devleaks** [comment]
I liked python-metar a lot, but I switched to [avwx-engine](https://engine.avwx.rest). It decodes METAR similarly, and TAF as well. A bit different though.
Using TAF rather than METAR to get a similar information in the future is just an idea that popped into my mind.
I use ATMAP to "normalize" wind speed and direction, precipitations, temperature, etc. in machine learning "categories".
P.

**Comment by devleaks** [comment]
There is also this library [python-metar-taf-parser](https://github.com/mivek/python-metar-taf-parser) which I haven’t used. However, it appears to maintain the parallel between Metar and TAF when decoding, which might ease our purpose.

**Comment by rebsp** [comment]
> I liked python-metar a lot, but I switched to [avwx-engine](https://engine.avwx.rest). It decodes METAR similarly, and TAF as well. A bit different though. Using TAF rather than METAR to get a similar information in the future is just an idea that popped into my mind. 

Just an update from my side to show you that this issue has not been forgotten! Summer holidays and good weather have slowed down my pace a bit. I'm currently rewriting things to AVWX, seems nice enough and actively maintained so I'll give it a shot.

>I use ATMAP to "normalize" wind speed and direction, precipitations, temperature, etc. in machine learning "categories". P.

I created it for the same purpose back in the day, glad to see that I'm not the only one 😉

**Comment by rebsp** [comment]
@devleaks there's a first draft of the new implementation available on the `taf` branch, you can check out a few examples in the `tests.py` file (or through #2 )

Let me know if this is what you were looking for.

**Comment by devleaks** [comment]
testing...
fails if taf.data.min_temp is None. (note taf.data.max_temp is also None.)
TAF=EBBR 280546Z 2806/2912 24008KT 9999 SCT008 BKN012 TEMPO 2806/2809 4000 RA SCT005 BKN008 PROB30 TEMPO 2806/2809 2500 RADZ BKN004 BECMG 2811/2813 SCT012 BKN020 PROB30 TEMPO 2810/2818 4500 SHRA BECMG 2820/2822 SCT035 PROB40 TEMPO 2909/2912 3500 SHRA TSRA SCT015CB

**Comment by devleaks** [comment]
```
line 183, in _get_wind_coef
    spd = self.data.wind_speed.value
```
can also be unavailable (`self.data.wind_speed` = None)

**Comment by devleaks** [comment]
```
line 301, in __get_visibility
    vis = self.data.visibility.value
```
can also be unavailable (`self.data.visibility.value` = None)

**Comment by devleaks** [comment]
I don't how we can deal with missing data... return a None coefficient to tell that evaluation could not be done?

**Comment by rebsp** [comment]
> I don't how we can deal with missing data... return a None coefficient to tell that evaluation could not be done?

Yeah makes sense, and within your preprocessing step probably keep the current METAR coefficient I guess...

**Comment by rebsp** [comment]
@devleaks updated the branch, please test again if you find the time

**Comment by devleaks** [comment]
```
    return self.data.temperature is not None or self.min_temp is not None
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TafLineData' object has no attribute 'temperature'
```
there is no temperature in tafLineData. There is temps (list) in tafData but it is None by default.
(do you have another messaging app? discord, slack, email?)

**Comment by rebsp** [comment]
>do you have another messaging app? discord, slack, email

nope, but I gave you collaborator access so you can push changes as well

**Comment by devleaks** [comment]
Thanks.

I now produce ATMAP from METAR and TAF without error.

A last thing, I think that as far as the TAF is, we should, if possible, also forward validity date/time information in the result, like a valid_from, valid_to pair of date/times to accompany the probability of realization (like you did).

BTW: This package is extremely valuable to model weather data (in general) for machine learning purpose. "Just" five values to code the "severity" of weather. Couldn't be simpler. I use it in aviation domain, so getting it from historical or current METAR or TAF for flights to come is extremely valuable. Thank you.

**Comment by devleaks** [comment]
Looks fine to me! Thank you!

**Comment by rebsp** [comment]
> A last thing, I think that as far as the TAF is, we should, if possible, also forward validity date/time information in the result, like a valid_from, valid_to pair of date/times to accompany the probability of realization (like you did).

I forwarded the `start_time` and `end_time` to the resulting dictionary.

> BTW: This package is extremely valuable to model weather data (in general) for machine learning purpose. "Just" five values to code the "severity" of weather. Couldn't be simpler. I use it in aviation domain, so getting it from historical or current METAR or TAF for flights to come is extremely valuable. Thank you.

Thank's for contributing!
